#----------------------------------------------------------------------
# This file was generated by generate_icon.py
# It contains base64-encoded PNG icons for use with PySide6
#

import base64
from PySide6.QtGui import QPixmap, QIcon
from PySide6.QtCore import QByteArray


def get_icon_from_base64(data_str):
    """Convert base64 string to QIcon"""
    try:
        byte_array = QByteArray.fromBase64(data_str.encode('ascii'))
        pixmap = QPixmap()
        pixmap.loadFromData(byte_array)
        return QIcon(pixmap)
    except Exception as e:
        print(f"Error loading icon: {e}")
        return QIcon()


# Icon catalog - maps icon names to base64-encoded PNG data
ICON_DATA = {
    'directions_run_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAB1klEQVRIS+2UP0vDQBiH3zdpldpq' \
    'UsTaVHBy0MHJb6DgJ9BJcFJHQWj9PxQUlRQUF0HBQRQ3P4CTH6CT6CDi4pKqg020tUKbnHdCsI1p' \
    'rtG6mSnh7p7n3t97F4Q/ftAvf1OSomIYpq2SsL+Yzxu89b4EO7IsV9ogb0PNki4v5sFT4kuQUaQV' \
    'QFy3BRYhyws5Y9OrCl+CdALawiAXbWBR00NpgPemCRiI9SAQxtniG+ymdV1vWg9oPOc0ntFPoFkZ' \
    'TD0WrnlwNu4Z0UZne3+wRczSWREnLKXpDcVbd1ImIRPvbMlFUjOGeVVwBWiRccsklxgUbp0wQipj' \
    '87nC2Y+abFfAosjEpS0QcOELRO5oun3sm5Z5dafpQwcAZTcRtwImUBPSMwJGbQAplxUSEEcEFE6q' \
    'oW59aUjg7Ec1SFXkI0SYZCJfguqdeQl+3GR74VY01CuGWu9rQIRYqZwh8uDce8Am0AjWaASrQOgD' \
    'eErfJ2xwI3ehpgc0Co2CYgTJsWnB3tLDS1ZVpEdEjNHzcpjSjClV6dhGFObqZe6syimoe7kQzIGk' \
    '9nrDANVHmBfTt1OkdoXjIIozKAgzdHGPWxy/ErjtKNMdidGf25M91nSBU/ov4B0MX+MfGfu7GVLV' \
    '0FYAAAAASUVORK5CYII=',
    'directions_run_48dp_8b1a10_fill0_wght400_grad0_opsz48': 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAD/UlEQVRoQ+2ZW4hNURjHv7XnHOEw' \
    'e7sMc7ak3EZeXIpIkUgeREkuhSjkRZrGGfKgeaI5Mw+SSB48eBEPbsmDWyQh5ZLcigdlz7i2jzEm' \
    'ZvZZ/htH++zWPmvtsfcZ6qzH/X17rf9vf9+31rfOYfSfD/af66cKgEoEW9L6XWJsxm/fRxnLnqLy' \
    'nopP7BHIpvVuxljCK4Zz3tPYlkuqCJT5xArQmta3cMaOBIjYjkgckAmU2WMFaEkb11Flc8Ui+J2M' \
    'lZslEyizxwqACBxFBDYJRXA6nmmz18sEyuyxAjQRJVKm0S0S0WnZSdh7ZAJl9lgB3MX3jho8Mcmr' \
    'nnuFdDOnbvebjhcycSr22AEKIuqJBugmsSaLvqoIU/UpG4CqoLB+sQG0po16TrQUghIapz0N7fa1' \
    'sOJU/CMFyNZUT2BJ7QoWHi1Y/D72/ekqosL4RALQnNa3aowdli3M83xlY3vulMwvjL3XANgC+6dM' \
    '/TwRWxhmQUSh12uK1gk9WbM5uE6jqtuYzBBMiLQv3eGiD3qKPmhyGOhSvqEBWkzDFVk8OH/nsO8z' \
    'dlldr4V2n7v23alr+NBH50CRQE6PO3vs2U3v6Yur8VdaGV0qXzeqVPqrCPhFZE19FSN2IgiAc3rF' \
    'GI39aefcybTlitpsFXC/T8QAxk1MOCdIiAuMy003Ljd/hKOtGI624mNvxLvvRApQMv853UD3OQ8F' \
    'xFpNI+8rohNordf0BqJ8APn8kkz75wsFkYB1IYrWd29qeHAMj58Adr8KUGQAKOB+KOBvpdLHb8ua' \
    'xlUImC96R7XIIwNordVXcI0FnrJBgpqqq4cOHMSeofhrvCCxASB/EeJfY4dlb/yTEmn9Iopzsehr' \
    'Iu8fNFr2NFlKZGtStSyRXA2/MUghdODyEToCQVOWKuA88UU7rdwluZzwHmUB4MR3Nlq5bHh58jci' \
    'AUABB959PRIOIq+3ySWF84gEAOmzDMueKSydJ2cSGr5nfimohXOoBdc3shEJAFqIy9hFFhRUuTvI' \
    'Pl0fkkixTwKlD2GfGhVBJAD+AvZsgez3gVWsF90r+qCRUUBED8D5aYhb7hUHCLdbTXmfqe7zMshA' \
    'APwseBwH/Vp0jfewvx8ixz6ZeUud/glRwBpOYKfwXCNnToPVccvvhybuLeYZ4U0zmTgVezCAabhi' \
    'B4omYZzfdTg71KXZpwaQsVAjOqsizJtq8UdAdPNS+CSlhJUVoKAVPw0OS+ar1hHjW9El1pVm4C/R' \
    'Fo8P8ukTAJGY7Ah9HK4km3HD2oA/L7y7Scnf/P8ZABFUc231zC7n85PC/Vjk808DKJQHVQAEXymS' \
    'g0zl67s+lQhUIqCaKwF+lRTq6xT6ywAKXy/rLhQHwA99+IBAPlCzFwAAAABJRU5ErkJggg==',
    'globe_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACTElEQVRIS72VP2/TQBjG73wOSCGx' \
    'IwFJnAlRqalCBxBIlIoBvgASolthQHwDwI66MRXqJF8BIdG5EgsrE38F6oBQC0V0i0vbIbFpkRr7' \
    'Xs6Bs2z3bDeVSqYk9/r9Pc9zr+8wOuIPPuL+KBPQOZ2/4Mm5JYzxmbAYAPjhuYOZua3d5TSRiYCF' \
    'U8W6dIysHsQhDOi4sWWviWqFAFNTnmMs3fYfAEC7APR6c8P+wBuYZXUMy/h7xBGlz4wN+24csg9g' \
    'aqofx02/EANcemj1P8UfatVKIHQGsKRb/VvhtQigXS00QJK/+AWk28vfR+g3L+5UlClKpLdZkdE9' \
    'b6K57XzldREAVwaud9XYdF6HmyWqFhD1bi/oG3xpa+pFwPgjAuToVk85cCwCgMuinfsXbQBoaeoq' \
    'wriOXG9a33T2RTGKAzbCK4bVbwz3kQvgDcL20vLOAvI+/x+QqBpgnY3g2cBxuXgFyeRNZCSpe45P' \
    'YaKDrDHMijAedRARe8HW4+eNCOafQWwDx0RrrWrhGpLkV4Bgzej2xyOb3CkXp6lMIrOf5CbJhVkr' \
    '7TDFeeTRKf2n/T4C8H9kTQYHigBcvV8jfNGGgEphEhH5s0h5WvaPaih/ApV2/OcouI2m9WtFeFT4' \
    'f7aryguQpBtxSBJgvqJczhHp3bA+67DjTU2ttIgxmg1D4oAnbM+ITF6yGvVvc7qoW/aduLDEC2f+' \
    'ZHEid5wEVtPGV9rz6g+2nW+imswr8zG7Momce8pG+HykAcCy6w7uHfrKTFM8ylqmg1GaiWr/ADAy' \
    '7hmHTL+9AAAAAElFTkSuQmCC',
    'info_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACeElEQVRIS91Vv2/TQBS+8zmUhiSO' \
    'BCRxxMCUVhEDqPxo6QJsLEgINmBA/Ae0Seg/0IDd8CcgJDpXYmEDFkD8KHRAqJRKsMUprUTslABN' \
    '7h5nOw6x4zhJpS548vk+v+973733DqM9fvAex0d9CUqHwyeoGFrCGB/tFAMAX2mzcXVus74SJLIn' \
    'wb1D0TFhH/k8SIbQYJn8prHuh/UlUOTYI4yF6+YPAKgOwM4XKsbbzgClZGySEeEZ/zZq4Rh7mK8Y' \
    'N70kXQSKLJl2XDaBGODkrKa/D8pCTUSnkEheWRiApZymX+nEuwgWUpEsCOInE0DK1fBthH4NYtH9' \
    'I2iUsnjdxLIdOl7Yqq05/7kI1HQcLBBlU4UN47U3uJqW/pjfcmV9xLunJKLTWCQv7P1qO277pShL' \
    'EyLGywiQkdOqkp9yTvC7RbDfd1+Ob/O6PAAIJvJl/YNlswNUZWkNYZwRuPoZH/WDWKUmpQuI4Ke8' \
    'hFfzmp51E7Ts6UxvkKDdNto2O3H+ZTAAgXNGQSK8mP+IgDfYN3Pe0CadvvO9ZjeO5+lnkZqKnEOC' \
    '+JxX0TqvoozrkEuJ6Fkmkpd8NNTyWjW2GwIlHf/JPQ8jyiZzG8YbF4G5aDcawKmCpi8Pk0GRqxe5' \
    '+p6NZhEkI8cQET+a70ONCj7waLo1KqCZLWjbq464rmG3kIo9BkG4ZKXH2OnZivEuqB/mk7EzISLY' \
    'Y6XfsHMCKXJ8EWN0zV7DD0ThouOpg7nLz4yI5Alf22MF2GJOM254xfS8cOYPRsdDI6SdalAWwg4d' \
    'm9mqffHD9L0yi/zKJGLoAS/h464AACvNZuPWrq/MIMXD7PXNYJhgfti/s3UYKJqhuqkAAAAASUVO' \
    'RK5CYII=',
    'logout_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAvklEQVRIS2NkoDFgpLH5DPS1oFec' \
    'z+IfM9NxfL4qffaBJEehKO6WEvhPKMioYgGphuBzFFYfDBoLuiT5ChkZmfiADmrE5QuyfdAgwCDA' \
    'zSXwHmpwAy5LyLYAZHCXCJcRIxvbWXyWUGQByOAeCT7T/0xMp3BZQpQFxCRfpDhACa7BYQG+dE6V' \
    'IMJlAU0juUOQgZ+ZU+ADbZMpLTMaoUIRJk9UKiLWMGzq6Fxci/FaMrAwH6NZhUNJUBBVmg5JCwDk' \
    'e3sZvHmHQgAAAABJRU5ErkJggg==',
    'settings_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACqElEQVRIS71VTWsTURS9b8baUG1e' \
    'oEqS+RVFaUFXlgq6ciP4sdKVKH6gyKQVrKbWRTMJKFhFl7pRwY1LMdWlmID5F5NUUsjEVg1m3vPM' \
    'NJPm48UUkjqbZGbuPefec+67w2iXL7bL+LQjgrQRkapCTLvSN79vgAc8VIKkQWNJm362VhwQBBV3' \
    '3gexqtyuDtIG/03ERolkNmc7J6fj/CsxdtgD6SSQUn7LF53pKYN/YMRmkVMzbSfUWlwbQSrKZzWd' \
    'ZZXGS5k3AeZLFuc5kE6p4oQrj8+tOavBuzaCoHWt/mfS1fULjGm3JMn1hO0cUIGh2zK6nZBSPKK6' \
    '+4qNjBRaO/X+NwmsGH/GNHaFJG2axcp+FaAV55cgy55fperzJJHojLGMyCYAx6Sgp4lS5VobAaqv' \
    '4AH3k6S8DDleBADpGD9DGnvbBijEPbNUXWrGRMPnSNdeN+4d+BVpI2iM4xP8+swg2da8xzkYtSuh' \
    'G0Q1ePIZnhxrgK8A/LrSA++hFQ/fhfZLUkgrUXLmIMtpxtg7pfEkFk27moQXFtQ24cVColh92Brb' \
    'Paax8AJp2gO0kMHImano+ClN198rCYRIQqZFy+AZjOltDMQdDMRyTwKYtALGq75CJD8hGLPd+yQH' \
    'EoEgu3UO/LwM8swuiVpNdl1xfn6t+iYIsqL8LNNZ894HEuJ+olRFp1vXMkzWmybLdXTvj/ZQxzQd' \
    'j2wAcR8JmTJLznwbQasULg6arusXiWk3UWsZ1RxUeQBpypBmAu08lnX35T8PmgfQZ1UUcDYO+YXE' \
    'eQFjOak0vu4eNb//+NLlQVNvg9dQ1V6YtZq3nRNYdt7e8YE7l513VnJF5wiW3UfkzMDhDWyB8Z5T' \
    '5L0YaF0ThZJE2Mbb1///4Kh0HeoXTWncAA93JNEA+PQXOdBGKHRfn9kAAAAASUVORK5CYII=',
    'update_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACHUlEQVRIS8VVT2vUUBCfSdquq3az' \
    'YGmbeBGhNyketofePCmIZ6EXC36Bekmqt4IF6eZQv4FQb3rqobSo4M1DRUrvXgSbRFow2bLtttt9' \
    '42zqK5uQvKxI2VyWTWbm9+fNzEO45AcvuT4MHmB1wrh9puE6U7mTUEv0qYlibsk7PFC5kKvgHYD+' \
    'wzKOAXBYaSNB0/bDUY4h16pSN9b2wou6mQDLN8o3S6XST1lYCHi6GIRveoFcs/IMUFuV79qHnbHh' \
    'UT1WowRYAtCuWdXO38QNDn6kUlA3jR1EvNsbowRgmUccXCaiD44fPUiwzrCg+71uVXfZimkZmwvg' \
    'TlwfB33oV1qmTEx7LP+nFeYDmMY2IM4IEk8W/cbbdOL/A+RYkKegnyFNdFFWm/VzBn3PQTFAPBdX' \
    'uOVPbC/i3+LnnxR0y7mW0WKQUhZI4aBxT3/lnq6REPNO0FjL4ydBCOjU8SIG41adNBzUcAWIvtl+' \
    'VJO5SQUFbdoLWLeMExS0bAeNl+fKztfEWVtMvdhvfM8EiAPNasSLrcJMNpnJw2KXY9u+sG2zbFuL' \
    'z6bcm5O5iyQbnuaPPM33VSCuaXzm2bnXjdn2wqH3AHLNxGmZACtjVy1tZGTvorAgxw4iN2GRWVlA' \
    '1F7Ld9Rum85+M0iTUV44ci+pFBDB0S0/rDxOMc89g3SxV3zh6DpsIeBU4hufUacVzT3/DZGKwOCv' \
    'zH66aKAK/gC+KugZDl+tkQAAAABJRU5ErkJggg==',
}


def get_icon(name):
    """Get QIcon by name from the catalog"""
    name = name.lower()
    if name in ICON_DATA:
        return get_icon_from_base64(ICON_DATA[name])
    print(f"Warning: Icon '{name}' not found in catalog")
    return QIcon()

